run-via-docker:
	docker run -it \
		-v $(pwd):/build \
		-e GIT_TOKEN="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" \
		-e TERRAFORM_CLOUD_TOKEN="ojODA5TvvwpL1A.atlasv1.6ifl0D5Q3zaonS3GPc5aXSLo4HWxCScaXf3u0sSVy4Eb4I62HAcs75W9l4EO9iBkFyE" \
		-e AWS_ACCESS_KEY_ID="54567898656" \
		-e AWS_SECRET_ACCESS_KEY="54567898656" \
		-e AWS_DEFAULT_REGION="54567898656" \
		dasmeta/meta create

export TF_VAR_git_token=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
export TF_VAR_tfc_token=ojODA5TvvwpL1A.atlasv1.6ifl0D5Q3zaonS3GPc5aXSLo4HWxCScaXf3u0sSVy4Eb4I62HAcs75W9l4EO9iBkFyE
export TFE_TOKEN=ojODA5TvvwpL1A.atlasv1.6ifl0D5Q3zaonS3GPc5aXSLo4HWxCScaXf3u0sSVy4Eb4I62HAcs75W9l4EO9iBkFyE
export TF_TOKEN_app_terraform_io=ojODA5TvvwpL1A.atlasv1.6ifl0D5Q3zaonS3GPc5aXSLo4HWxCScaXf3u0sSVy4Eb4I62HAcs75W9l4EO9iBkFyE
